title: Amy Feng
description: Data Analyst and Visualization Expert
### Hi There

_My name is Amy Feng, a Data Analyst and Visualization Expert._

Passionate about using visualization to communicate insights effectively, enabling businesses to make data-driven decisions with confidence and clarity. Let's exploring the beauty of nature data!
theme: jekyll-theme-minimal
